const mongoose = require("mongoose");
// name,ab_battles,ab_win_rate,ab_air_frags_per_battle,ab_air_frags_per_death,ab_ground_frags_per_battle,ab_ground_frags_per_death,
// rb_battles,rb_win_rate,rb_air_frags_per_battle,rb_air_frags_per_death,rb_ground_frags_per_battle,rb_ground_frags_per_death,
// sb_battles,sb_win_rate,sb_air_frags_per_battle,sb_air_frags_per_death,sb_ground_frags_per_battle,sb_ground_frags_per_death,
// alt_name,wk_name,nation,cls,ab_br,rb_br,sb_br,
// for newer data: ab_repair,rb_repair,sb_repair,is_premium,ab_rp_rate,ab_sl_rate,rb_rp_rate,rb_sl_rate,sb_rp_rate,sb_sl_rate
const VehicleSchema = new mongoose.Schema({
  date: Date,
  name: String,
  ab_battles: Number,
  ab_win_rate: Number,
  ab_air_frags_per_battle: Number,
  ab_air_frags_per_death: Number,
  ab_ground_frags_per_battle: Number,
  ab_ground_frags_per_death: Number,
  rb_battles: Number,
  rb_win_rate: Number,
  rb_air_frags_per_battle: Number,
  rb_air_frags_per_death: Number,
  rb_ground_frags_per_battle: Number,
  rb_ground_frags_per_death: Number,
  sb_battles: Number,
  sb_win_rate: Number,
  sb_air_frags_per_battle: Number,
  sb_air_frags_per_death: Number,
  sb_ground_frags_per_battle: Number,
  sb_ground_frags_per_death: Number,
  wk_name: String,
  nation: String,
  cls: String,
  ab_br: Number,
  rb_br: Number,
  sb_br: Number,
  // Newer
  ab_repair: Number,
  rb_repair: Number,
  sb_repair: Number,
  is_premium: Boolean,
  ab_rp_rate: Number,
  ab_sl_rate: Number,
  rb_rp_rate: Number,
  rb_sl_rate: Number,
  sb_rp_rate: Number,
  sb_sl_rate: Number,
});

module.exports = mongoose.model("vehicle", VehicleSchema, "joined");
